spring.application.name=AquilerApi

# ACCESO A LA BASE DE DATOS
# NuevaContra123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/alquilerAutosbd?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=NuevaContra123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

logging.level.org.springframework.web=DEBUG
